# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    /(
        \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | build
      | dist
      | micropy/lib
    )/
    | foo.py
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.255"
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-export
        args:
          - -f
          - requirements.txt
          - -o
          - docs/requirements.txt
          - --with
          - docs
          - --without-hashes

ci:
  skip:
    # todo: well-overdue update of docs
    - poetry-export
  autofix_commit_msg: "ci(pre-commit.ci): 🎨 Auto format from pre-commit.com hooks"
  autoupdate_commit_msg: "ci(pre-commit.ci): ⬆ pre-commit autoupdate"
