# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
      /(
          \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | build
        | dist
        | micropy/lib
      )/
      | foo.py
    )$

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: check-executables-have-shebangs
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args:
                - "--recursive"
                - "--in-place"
                - "--remove-all-unused-imports"
                - "--ignore-init-module-imports"
    - repo: https://github.com/psf/black
      rev: 21.5b1
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort

    - repo: https://github.com/python-poetry/poetry
      rev: 1.2.0b1
      hooks:
          - id: poetry-check
          # Does not seem to use poetry-export plugin :(
          #- id: poetry-export
          #args: [ "-f", "requirements.txt", "-o", "docs/requirements.txt", "--with", "docs", "--dev", "--without-hashes" ]

    - repo: local
      hooks:
          - id: poetry-export
            name: poetry-export
            language: script
            files: (pyproject\.toml|poetry\.lock)$
            entry: ./scripts/export-docs-reqs.sh
