
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='micropy-cli',
    version='3.5.0',
    description='Micropython Project Management Tool with VSCode support, Linting, Intellisense, Dependency Management, and more!',
    python_requires='<3.10,>=3.6',
    project_urls={"documentation": "https://micropy-cli.readthedocs.io", "homepage": "https://github.com/BradenM/micropy-cli", "repository": "https://github.com/BradenM/micropy-cli"},
    author='Braden Mars',
    author_email='bradenmars@bradenmars.me',
    license='MIT',
    keywords='micropython stubs linting vscode intellisense',
    classifiers=['Topic :: Software Development :: Code Generators', 'Topic :: Software Development :: Embedded Systems', 'Topic :: Software Development :: Build Tools', 'Programming Language :: Python :: Implementation :: MicroPython', 'Programming Language :: Python :: Implementation :: CPython', 'Development Status :: 5 - Production/Stable', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License'],
    entry_points={"console_scripts": ["micropy = micropy.cli:cli"]},
    packages=['micropy', 'micropy.config', 'micropy.data', 'micropy.lib.stubber.tests', 'micropy.packages', 'micropy.project', 'micropy.project.modules', 'micropy.stubs', 'micropy.utils'],
    package_dir={"": "."},
    package_data={"micropy": ["lib/stubber/*.conf", "lib/stubber/*.ini", "lib/stubber/*.md", "lib/stubber/*.txt", "lib/stubber/*.yml", "lib/stubber/.github/*.yml", "lib/stubber/.github/workflows/*.yml", "lib/stubber/.vscode/*.json", "lib/stubber/data/*.txt", "lib/stubber/data/ignore/*.txt", "lib/stubber/data/pycom_ignore/*.txt", "lib/stubber/docs/*.yml", "lib/stubber/docs/img/*.PNG", "lib/stubber/docs/img/*.gif", "lib/stubber/docs/img/*.png", "lib/stubber/patches/*.patch", "lib/stubber/scripts/*.ps1", "lib/stubber/src/*.cfg", "lib/stubber/src/*.md", "lib/stubber/src/*.txt"], "micropy.data": ["*.json", "schemas/*.json"], "micropy.lib.stubber.tests": ["*.md", "mocks/micropython-cpython_core/*.md", "mocks/pycopy-cpython_core/*.json", "mocks/pycopy-cpython_core/*.md", "mocks/pycopy-cpython_core/*.pyi"], "micropy.project": ["template/*.conf", "template/.vscode/*.json"]},
    install_requires=['boltons==19.*,>=19.3.0', 'cachier==1.*,>=1.2.0', 'click==7.*,>=7.0.0', 'colorama==0.*,>=0.4.3; sys_platform == "win32"', 'dpath<2.0,>=1.4', 'gitpython==3.*,>=3.1.7', 'jinja2==2.*,>=2.10.0', 'jsonschema==3.2.0', 'packaging<21.0,>=19.2', 'questionary==1.*,>=1.8.1', 'requests==2.*,>=2.22.0', 'requirements-parser==0.*,>=0.2.0', 'tqdm==4.*,>=4.39.0'],
    dependency_links=['/home/bradenmars/projects/micropy/micropy-cli'],
    extras_require={"create_stubs": ["pyminifier==2.*,>=2.1.0", "rshell==0.*,>=0.0.26"], "dev": ["autoflake==1.*,>=1.4.0", "autopep8==1.*,>=1.5.0", "bump2version==0.*,>=0.5.11", "codacy-coverage==1.*,>=1.3.0", "coveralls==3.*,>=3.0.0", "doc8==0.*,>=0.8.0", "docformatter==1.*,>=1.4.0", "flake8==3.*,>=3.9.0", "flaky==3.*,>=3.7.0", "isort==5.*,>=5.8.0", "micropy-cli[create_stubs,docs]", "mypy==0.*,>=0.812.0", "pylint==2.*,>=2.7.0", "pytest==6.*,>=6.2.0", "pytest-cov==2.*,>=2.11.0", "pytest-datadir==1.*,>=1.3.0", "pytest-forked==1.*,>=1.3.0", "pytest-mock==3.*,>=3.5.0", "pytest-randomly==3.*,>=3.7.0", "pytest-runner==5.*,>=5.3.0", "pytest-sugar==0.*,>=0.9.4", "pytest-testmon==1.*,>=1.0.0", "pytest-watch==4.*,>=4.2.0", "pytest-xdist==1.*,>=1.30.0", "requests-mock==1.*,>=1.9.0", "rope==0.*,>=0.19.0", "tox==3.*,>=3.23.0", "tox-gh-actions==0.*,>=0.3.0"], "docs": ["recommonmark==0.*,>=0.6.0", "sphinx==2.*,>=2.2.0", "sphinx-autodoc-typehints==1.*,>=1.10.3", "sphinx-click==2.*,>=2.3.0", "sphinx-rtd-theme==0.*,>=0.4.3"]},
)
