name: Changelog

on:
  push:
    branches:
      - master

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v3

      - name: Install gh-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Generate Changelog
        run: git-chglog

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore(chglog): update changelog." -a || true

      - name: Push Changes
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}
