name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_PAT }}
          command: manifest
