name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        # see: googleapis/release-please#1837
        uses: BradenM/release-please-action@661b5aac32c2caa7ccbaff42d32cb01d35a6797b
        with:
          token: ${{ secrets.GH_PAT }}
          command: manifest
