name: Release

on:
  push:
    branches:
      - master

env:
  POETRY_VERSION: 1.3.2
  PYTHON_VERSION: 3.11

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          # mark gh releases as pre (IF version is a semantic pre)
          prerelease: true

  publish:
    name: Publish ${{ needs.release-please.outputs.tag_name }}
    runs-on: ubuntu-latest
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup environment.
        uses: ./.github/actions/setup-micropy
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build
        run: poetry build

      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
